---
'182358771':
  title: 'Interessant3 #173 | UK Net Migration, Pay Transparency Laws, Geography &
    Logistics in WWII'
  file: 2025-12-28-interessant3-173-uk-net-migration-pay-transparency.markdown
  pulled_at: '2026-01-01T13:35:30+01:00'
'182352763':
  title: 'Interessant3 #172 | Social Mobility, English Interest, AI Companies'
  file: 2025-12-23-interessant3-172-social-mobility-english-interest-.markdown
  pulled_at: '2026-01-01T13:35:30+01:00'
'182343985':
  title: 'Interessant3 #171 | Genius Investors, Economics Disconnect, Exercise and
    Stress'
  file: 2025-12-23-interessant3-171-genius-investors-economics-discon.markdown
  pulled_at: '2026-01-01T13:35:30+01:00'
'182340343':
  title: 'Interessant3 #170 | Data Centre Water Usage, IndieHacker Tips, Philosopher-Builder
    Reads'
  file: 2025-12-23-interessant3-170-data-centre-water-usage-indiehack.markdown
  pulled_at: '2026-01-01T13:35:30+01:00'
'182334229':
  title: 'Interessant3 #169 | Elite Talent, Lessons from French Nuclear, The AI Work
    Boom'
  file: 2025-12-23-interessant3-169-elite-talent-lessons-from-french-.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'179751670':
  title: "Interessant3 #168 | \U0001F9E0Constitution of Innovation, \U0001F3DB️Roman
    Labour Supply, \U0001F476Global Poverty News"
  file: 2025-11-23-interessant3-168-constitution-of-innovation-roman-.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'179071283':
  title: "Interessant3 #167 | \U0001F1EB\U0001F1EEThe Resilience of Sisu,\U0001F4A7Desalination
    Economics, \U0001F9ECGenetics & Meritocracy"
  file: 2025-11-16-interessant3-167-the-resilience-of-sisudesalinatio.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'178447168':
  title: "Interessant3 #166 | \U0001F4F0Media Bias, \U0001F333Brazilian Forests, ☀️Solarpunk
    in Africa"
  file: 2025-11-09-interessant3-166-media-bias-brazilian-forests-sola.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'177818751':
  title: "Interessant3 #165 | \U0001F476Income→Parenthood, \U0001F4C9EU Debt Swaps,
    \U0001F916LLM Moral Trade-offs"
  file: 2025-11-02-interessant3-165-incomeparenthood-eu-debt-swaps-ll.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'177815827':
  title: "Interessant3 #164 | \U0001F9EDIncentives, \U0001F5E3️Language & Code, \U0001F4CAUK
    Productivity"
  file: 2025-11-02-interessant3-164-incentives-language-code-uk-produ.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'176589227':
  title: "Interessant3 #163 | \U0001F3D8️Bamako urbanism, \U0001F1EB\U0001F1F7Macron
    & momentum, \U0001F3C5Econ Nobel 2025"
  file: 2025-10-19-interessant3-163-bamako-urbanism-macron-momentum-e.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'175967514':
  title: "Interessant3 #162 | \U0001F31E Fatima Sun Miracle, \U0001F9E0 Agent Detection,
    \U0001F1EA\U0001F1FA EuropeVersus"
  file: 2025-10-12-interessant3-162-fatima-sun-miracle-agent-detectio.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'175359418':
  title: "Interessant3 #161 | \U0001F3E0Housing Supply & Prices, \U0001F4CAInequality
    in Tax Evasion, \U0001F333Amazon’s Big Trees"
  file: 2025-10-05-interessant3-161-housing-supply-prices-inequality-.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'175357940':
  title: "Interessant3 #160 | \U0001FAB4Against Edenism, \U0001F310Anguilla’s AI Windfall,
    \U0001F4F0Pravda’s Silence"
  file: 2025-10-05-interessant3-160-against-edenism-anguillas-ai-wind.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'175356409':
  title: "Interessant3 #159 | \U0001F916AI & Radiology, \U0001F31EFátima’s Sun, \U0001F4C8Freedom
    & the Poorest"
  file: 2025-10-05-interessant3-159-ai-radiology-ftimas-sun-freedom-t.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'174367457':
  title: "Interessant3 #158 | \U0001F3E0UK Property, \U0001F33EBrazilian Agriculture,
    \U0001F4F1LLM Red Flags"
  file: 2025-09-23-interessant3-158-uk-property-brazilian-agriculture.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'173126848':
  title: "Interessant3 #157 | ☀️Solar Reality Check, \U0001F4ACLaconism, \U0001F6A2How
    To Ship"
  file: 2025-09-08-interessant3-157-solar-reality-check-laconism-how-.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'172261776':
  title: "Interessant3 #156 | \U0001F9E0IQ Worries, \U0001F30AGeopolitical Power,
    \U0001F48EWoke Economics"
  file: 2025-08-31-interessant3-156-iq-worries-geopolitical-power-wok.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'171836515':
  title: "Interessant3 #155 | \U0001F30D Immigration & Institutions, \U0001F9E9 The
    Legibility Bottleneck, \U0001F9E0 Meta-Thinking"
  file: 2025-08-24-interessant3-155-immigration-institutions-the-legi.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'171220986':
  title: "Interessant3 #154 | \U0001F916 AI & Jobs, \U0001F3AC Peak Cinema, \U0001F6F0️
    NASA Landsat Names"
  file: 2025-08-17-interessant3-154-ai-jobs-peak-cinema-nasa-landsat-.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'171220301':
  title: "Interessant3 #153 | \U0001F916Claude Code, \U0001F4BBOffline AI, \U0001F321️
    European Heatwaves"
  file: 2025-08-17-interessant3-153-claude-code-offline-ai-european-h.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'171216625':
  title: "Interessant3 #152 | \U0001F9E0 Fertility & IQ, ⚡ Nat Friedman’s Beliefs,
    \U0001F4B8 Startup Decks"
  file: 2025-08-17-interessant3-152-fertility-iq-nat-friedmans-belief.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'171214782':
  title: "Interessant3 #151 | \U0001F6CC Insomnia Algorithm, \U0001F9E0 Cognitive
    Advance, \U0001F3F4 Catalan Privilege"
  file: 2025-08-17-interessant3-151-insomnia-algorithm-cognitive-adva.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'168815161':
  title: "Interessant3 #150 | \U0001F5A5 JavaScript Freedom, \U0001F680 Bootstrapped
    ARR, \U0001F4C8 Free-Market Resurgence"
  file: 2025-07-21-interessant3-150-javascript-freedom-bootstrapped-a.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'168812903':
  title: "Interessant3 #149 | \U0001F3E0 Rent Control, \U0001F30D Global Health Futures,
    \U0001F426 Family Ties on Twitter"
  file: 2025-07-21-interessant3-149-rent-control-global-health-future.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'167670167':
  title: "Interessant3 #148 | \U0001F916 Strategic LLMs, \U0001F4B0 Racial Diversity
    Economics, \U0001F36F Honey Ethics"
  file: 2025-07-06-interessant3-148-strategic-llms-racial-diversity-e.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'167116899':
  title: "Interessant3 #147 | \U0001F9ECLife Extension, \U0001F1EA\U0001F1F8 Spanish
    Wage Stagnation, \U0001F6E0 Indie-Hacker Playbook"
  file: 2025-06-29-interessant3-147-life-extension-spanish-wage-stagn.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'166416310':
  title: "Interessant3 #146 | \U0001F3D8️Spanish Land, \U0001F32A️Geoengineering,
    \U0001F4C8Housing Supply"
  file: 2025-06-22-interessant3-146-spanish-land-geoengineering-housi.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'166411359':
  title: "Interessant3 #145 | \U0001F3D8️Housing Supply Scepticism, \U0001F680Engineering
    Futures, \U0001F9E0Psychological Sex Differences"
  file: 2025-06-22-interessant3-145-housing-supply-scepticism-enginee.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'166395275':
  title: "Interessant3 #144 | \U0001F916LLM Bias, ⚠️Trigger Warnings, \U0001F9E9Rosetta
    Stone"
  file: 2025-06-21-interessant3-144-llm-bias-trigger-warnings-rosetta.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'166392985':
  title: "Interessant3 #143 | \U0001F1EC\U0001F1E7 Britain’s Triage, ⚛️ Lead to Gold,
    \U0001F468‍\U0001F3EB Economist Jones"
  file: 2025-06-21-interessant3-143-britains-triage-lead-to-gold-econ.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'166142598':
  title: "Interessant3 #142 | \U0001F4A5AI Boom, \U0001F9E0Truth Shifts, \U0001F9ECCaste-by-Choice"
  file: 2025-06-20-interessant3-142-ai-boom-truth-shifts-caste-by-cho.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'163963314':
  title: "Interessant3 #141 | \U0001F9EACareer Experiments, \U0001F916Innovation Surplus,
    ☯︎Virtuous Balance"
  file: 2025-05-19-interessant3-141-career-experiments-innovation-sur.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'163959714':
  title: "Interessant3 #140 | \U0001F501 Fundraising Loops, \U0001F9E0 Science Without
    Results, \U0001F4AB Gold from Lead"
  file: 2025-05-19-interessant3-140-fundraising-loops-science-without.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'162839416':
  title: "Interessant3 #139 | \U0001F680 Old-School Science Sites, \U0001F310 The
    Future Revisited, \U0001F9E0 Trivial Decisions"
  file: 2025-05-04-interessant3-139-old-school-science-sites-the-futu.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'162287420':
  title: "Interessant3 #138 | \U0001F3A8 Deep Learning's History, \U0001F4DA Feminisation
    & Progress, \U0001F9E0 Falsificationism"
  file: 2025-04-27-interessant3-138-deep-learnings-history-feminisati.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'161744866':
  title: "Interessant3 #137 | \U0001F525 Wildfire Data, \U0001F9C3 Being Basic, \U0001F399️
    Dominic Cummings on Dwarkesh"
  file: 2025-04-20-interessant3-137-wildfire-data-being-basic-dominic.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'161253855':
  title: "Interessant3 #136 | \U0001F916 AI Alignment, \U0001F3D7️ Tract’s Postmortem,
    \U0001F3A4 Rogan’s Comedy Club"
  file: 2025-04-13-interessant3-136-ai-alignment-tracts-postmortem-ro.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'160725533':
  title: "Interessant3 #135 | \U0001F9EC Secular religion, \U0001F4F1Android's privacy
    violations, \U0001F916 GPT-4.5 passes the Turing test"
  file: 2025-04-06-interessant3-135-secular-religion-androids-privacy.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'160286856':
  title: "Interessant3 #134 | ✈️ How Airbus Took Off, \U0001F5FA️ Palestinian Statelessness,
    \U0001F40B Right Whales Return"
  file: 2025-03-31-interessant3-134-how-airbus-took-off-palestinian-s.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'159708182':
  title: "Interessant3 #133 | \U0001FA90 Dark Cosmos, \U0001F4C9 Prices and Inflation,
    \U0001F9E9 Model Context Protocols"
  file: 2025-03-23-interessant3-133-dark-cosmos-prices-and-inflation-.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'159334734':
  title: 'Interessant3 #132'
  file: 2025-03-18-interessant3-132.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'158731138':
  title: 'Interessant3 #131'
  file: 2025-03-09-interessant3-131.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'158257653':
  title: 'Interessant3 #130'
  file: 2025-03-03-interessant3-130.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'157773617':
  title: 'Interessant3 #129'
  file: 2025-02-24-interessant3-129.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'157282408':
  title: 'Interessant3 #128'
  file: 2025-02-16-interessant3-128.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'156816002':
  title: 'Interessant3 #127'
  file: 2025-02-09-interessant3-127.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'156786456':
  title: 'Interessant3 Long Form #2: Tuition Fees'
  file: 2025-02-09-interessant3-long-form-2-tuition-fees.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'156324887':
  title: 'Interessant3 #126'
  file: 2025-02-02-interessant3-126.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
'155792312':
  title: 'Interessant3 #125'
  file: 2025-01-26-interessant3-125.markdown
  pulled_at: '2026-01-01T13:35:32+01:00'
